/*
 * Appointment Scheduling Api
 *
 * Medical Appointment Scheduling System
 *
 * API version: 1.0.0
 * Contact: xpokorny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type AppointmentsAPI interface {


    // CreateAppointment Post /api/appointments
    // Create a new appointment 
     CreateAppointment(c *gin.Context)

    // DeleteAppointment Delete /api/appointments/:appointmentId
    // Delete an appointment 
     DeleteAppointment(c *gin.Context)

    // GetAppointment Get /api/appointments/:appointmentId
    // Get appointment details 
     GetAppointment(c *gin.Context)

    // GetAppointments Get /api/appointments
    // Get all appointments 
     GetAppointments(c *gin.Context)

    // UpdateAppointment Put /api/appointments/:appointmentId
    // Update an appointment 
     UpdateAppointment(c *gin.Context)

}