/*
 * Appointment Scheduling Api
 *
 * Medical Appointment Scheduling System
 *
 * API version: 1.0.0
 * Contact: xpokorny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type UsersAPI interface {


    // GetUser Get /api/users/:userId
    // Get user details 
     GetUser(c *gin.Context)

    // GetUsers Get /api/users
    // Get all users 
     GetUsers(c *gin.Context)

}