/*
 * Appointment Scheduling Api
 *
 * Medical Appointment Scheduling System
 *
 * API version: 1.0.0
 * Contact: xpokorny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type LocationsAPI interface {


    // GetLocations Get /api/locations
    // Get all locations 
     GetLocations(c *gin.Context)

}