/*
 * Appointment Scheduling Api
 *
 * Medical Appointment Scheduling System
 *
 * API version: 1.0.0
 * Contact: xpokorny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AppointmentsAPI part of the API
	AppointmentsAPI AppointmentsAPI
	// Routes for the LocationsAPI part of the API
	LocationsAPI LocationsAPI
	// Routes for the UsersAPI part of the API
	UsersAPI UsersAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateAppointment",
			http.MethodPost,
			"/api/appointments",
			handleFunctions.AppointmentsAPI.CreateAppointment,
		},
		{
			"DeleteAppointment",
			http.MethodDelete,
			"/api/appointments/:appointmentId",
			handleFunctions.AppointmentsAPI.DeleteAppointment,
		},
		{
			"GetAppointment",
			http.MethodGet,
			"/api/appointments/:appointmentId",
			handleFunctions.AppointmentsAPI.GetAppointment,
		},
		{
			"GetAppointments",
			http.MethodGet,
			"/api/appointments",
			handleFunctions.AppointmentsAPI.GetAppointments,
		},
		{
			"UpdateAppointment",
			http.MethodPut,
			"/api/appointments/:appointmentId",
			handleFunctions.AppointmentsAPI.UpdateAppointment,
		},
		{
			"GetLocations",
			http.MethodGet,
			"/api/locations",
			handleFunctions.LocationsAPI.GetLocations,
		},
		{
			"GetUser",
			http.MethodGet,
			"/api/users/:userId",
			handleFunctions.UsersAPI.GetUser,
		},
		{
			"GetUsers",
			http.MethodGet,
			"/api/users",
			handleFunctions.UsersAPI.GetUsers,
		},
	}
}
